docs: front page
starkware-libs/starknet-docs pull request #17
Opened 2022-03-01 09:36 UTC by ArielElp

### Description of the Changes

Please add a detailed description of the change, whether it's an enhancement or a bugfix.
If the PR is related to an open issue please link to it.

### Check List

- [ ] Changes have been done against dev branch, and PR does not conflict
- [ ] Docs have been updated
- [ ] PR title is follow the convention: `<docs/feat/fix/chore>(optional scope): <description>`, e.g: `fix: minor typos in code`

2022-03-01 11:19 UTC, bbrandtom requested changes
Tried using GitHub review - let me know how it works.

2022-03-01 11:19 UTC, bbrandtom commented on src/config/home.json
> +    "text": "Introduction to StarkNet: how it works, main concepts glossary, FAQs"
We don't have an intro to StarkNet yet. I would change this sentence to describe the technical docs. We don't have a glossary nor FAQs here.

2022-03-01 11:19 UTC, bbrandtom commented on src/config/home.json
>      "title": "what is starkNet",
```suggestion
    "title": "What is StarkNet",
```

2022-03-01 11:19 UTC, bbrandtom commented on src/config/home.json
> +    "text": "Your StarkNet first steps"
maybe "Your first steps in StarkNet"

2022-03-01 11:19 UTC, bbrandtom commented on src/config/home.json
> +    "text": "StarkNet newsletter"
```suggestion
    "text": "StarkNet's unofficial newsletter"
```

2022-03-10 20:26 UTC, ArielElp reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-docs/17)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @bbrandtom)

___
*[src/config/home.json, line 5 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/17#-MxpSsVYTJjBp68hYRG6-r1-5:-MxpTOce-VcfhprofQk8:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/223ea225f1bb912862b5e852bf2af984be1e409d/src/config/home.json#L5)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

```suggestion
    "title": "What is StarkNet",
```
</blockquote></details>

Done.
___
*[src/config/home.json, line 6 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/17#-MxpSsVYTJjBp68hYRG6-r1-6:-MxpUgtM5pAJhO5sjAl0:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/223ea225f1bb912862b5e852bf2af984be1e409d/src/config/home.json#L6)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

We don't have an intro to StarkNet yet. I would change this sentence to describe the technical docs. We don't have a glossary nor FAQs here.
</blockquote></details>

Done.
___
*[src/config/home.json, line 12 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/17#-MxpSsVYTJjBp68hYRG6-r1-12:-MxpTwQc0epKRV5n8t4S:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/223ea225f1bb912862b5e852bf2af984be1e409d/src/config/home.json#L12)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

maybe "Your first steps in StarkNet"
</blockquote></details>

Done.
___
*[src/config/home.json, line 30 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/17#-MxpSsVYTJjBp68hYRG6-r1-30:-MxpU3z90hYG5urPeYXi:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/223ea225f1bb912862b5e852bf2af984be1e409d/src/config/home.json#L30)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

```suggestion
    "text": "StarkNet's unofficial newsletter"
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-11 08:32 UTC, bbrandtom reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-docs/17#-:-Mxs5lxo7dpuCs3_wwA9:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @bbrandtom)



<!-- Sent from Reviewable.io -->

2022-03-12 07:44 UTC, ArielElp reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-docs/17#-:-Mxx4QC496-4krGf5o9I:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @bbrandtom)



<!-- Sent from Reviewable.io -->

2022-03-12 10:16 UTC, ArielElp reviewed
> Dismissed @bbrandtom from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-docs/17)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ArielElp)



<!-- Sent from Reviewable.io -->

2022-03-12 10:16 UTC, merged